import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import './style.css';
import {setupTraining} from './training.js';
document.querySelector('#app').innerHTML=`<header><div class="brand"><span class="mark">◈</span> ORIGIN <small>Embodied intelligence lab</small></div><span class="badge">ENVIRONMENT 001</span></header><main><section class="viewport"><div class="scene-label"><span class="dot"></span> Learning playground <small>3D physics · 12 actuated joints · articulated quadruped</small></div><canvas id="world"></canvas><div class="scene-bottom"><span>Drag to orbit · Scroll to zoom</span><span id="clock">00:00</span></div></section><aside><div class="eyebrow">EXPERIMENT CONTROLS</div><h1>A world to<br>learn in.</h1><p>A small beginning for an expanding intelligence. Explore the body, its senses, and its possibilities.</p><label>Viewer<select id="view"><option value="training">Training · live world 1</option><option value="demo">Demonstration · separate world</option></select></label><div id="demo-controls"><label>Controller<select id="mode"><option value="idle">Stand · neutral posture</option><option value="explore">Exploration · scripted movement</option><option value="manual">Manual · arrow keys / WASD</option></select></label><div class="notice">These are demonstration controls, not the training policy. Exploration uses a fixed movement pattern.</div><div class="buttons"><button id="pause">Pause</button><button id="reset">Reset world</button></div><label>World seed<input id="seed" type="number" value="1" min="1" max="999999"></label></div><div class="notice" id="training-view-notice">Start learning in the lab below. This view will display the actual training creature; joint actions come from its neural policy. <a href="#training-panel">Open learning lab ↓</a></div><div class="section-title">BODY OBSERVATIONS <span>LIVE</span></div><div id="stats"></div><div class="section-title">JOINT POSITION COMMANDS</div><div id="motors"></div><div class="section-title">FOOT CONTACTS / NEWTONS</div><div id="feet"></div><div class="section-title">NEXT MILESTONE</div><p class="next">PPO learns independent joint commands. Compare held-out evaluation results with the baseline to judge improvement.</p></aside></main><footer><span><i></i> Local simulation</span><span>Physics → observations → actions → physics</span><span>v0.1 / Foundation</span></footer>`;
const canvas=document.querySelector('#world'),renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x0b171d);scene.fog=new T.Fog(0x0b171d,22,48);
const camera=new T.PerspectiveCamera(45,1,.1,100);camera.position.set(11,9,13);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,.4,2);controls.enableDamping=true;controls.maxPolarAngle=Math.PI/2-.03;
scene.add(new T.HemisphereLight(0xd4fff2,0x263140,2));const sun=new T.DirectionalLight(0xffebd1,3);sun.position.set(5,12,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14});scene.add(sun);
const grid=new T.GridHelper(24,24,0x42716c,0x294143);grid.position.y=.015;scene.add(grid);
const target=new T.Mesh(new T.TorusGeometry(.65,.045,12,64),new T.MeshBasicMaterial({color:0x70e6c4}));target.rotation.x=-Math.PI/2;target.position.set(0,.05,7);scene.add(target);
let sim=null,meshes=[],paused=false;
const connection=document.querySelector('footer span');
connection.textContent='Connecting to Python physics…';
const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/physics`);
function send(message){if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message));}
socket.onopen=()=>{connection.textContent='Python physics · connected';sendControl();};
socket.onclose=()=>{connection.textContent='Physics disconnected · restart backend and reload';sim=null;};
socket.onerror=()=>{connection.textContent='Python physics unavailable';};
function applyScene(state){sim=state;
 if(motors.children.length!==state.joints.length)motors.innerHTML=state.joints.map(j=>`<div class="motor"><span>${j.name.replace('hip_','')}</span><div><b></b></div><small></small></div>`).join('');
 if(meshes.length!==state.bodies.length){for(const mesh of meshes){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}
 meshes=state.bodies.map(({size,color})=>{const mesh=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color,roughness:.7,metalness:.1}));mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);return mesh;});}
}
socket.onmessage=event=>{const state=JSON.parse(event.data);if(state.error){connection.textContent=state.error;return;}if(document.querySelector('#view').value==='demo')applyScene(state);};
document.querySelector('#reset').onclick=()=>{const seed=Number(document.querySelector('#seed').value);if(Number.isInteger(seed)&&seed>=1&&seed<=999999)send({type:'reset',seed});else document.querySelector('#seed').reportValidity();};
document.querySelector('#pause').onclick=()=>{paused=!paused;document.querySelector('#pause').textContent=paused?'Resume':'Pause';sendControl();};
const keys=new Set();window.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());
const stats=document.querySelector('#stats'),motors=document.querySelector('#motors');stats.innerHTML=['Body height','Uprightness','Speed','Target distance'].map(label=>`<div class="stat"><span>${label}</span><strong></strong></div>`).join('');
function sendControl(){const drive=Number(keys.has('w')||keys.has('ArrowUp'))-Number(keys.has('s')||keys.has('ArrowDown'));const turn=Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft'));send({type:'control',mode:document.querySelector('#mode').value,drive,turn,paused:paused||document.querySelector('#view').value==='training'});}
const training=setupTraining(state=>{if(document.querySelector('#view').value==='training'){applyScene(state);connection.textContent='Live training · world 1';}});
function changeView(){const trainingView=document.querySelector('#view').value==='training';document.querySelector('#demo-controls').hidden=trainingView;document.querySelector('#training-view-notice').hidden=!trainingView;sim=null;for(const mesh of meshes){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}meshes=[];document.querySelector('.scene-label small').textContent=trainingView?'Actual training world 1 · policy controls all 12 joints':'Separate demonstration world · scripted/manual controls';sendControl();if(trainingView)training.show();}
document.querySelector('#view').onchange=changeView;
changeView();
document.querySelector('#mode').onchange=sendControl;
window.addEventListener('keydown',sendControl);window.addEventListener('keyup',sendControl);window.addEventListener('blur',sendControl);
function frame(){if(sim){
meshes.forEach((m,i)=>{m.position.fromArray(sim.bodies[i].position);m.quaternion.fromArray(sim.bodies[i].quaternion);});const o=sim.observations;const values=[`${o.height.toFixed(2)} m`,`${Math.round(o.upright*100)}%`,`${o.speed.toFixed(2)} m/s`,`${o.distance.toFixed(2)} m`];stats.querySelectorAll('strong').forEach((el,i)=>el.textContent=values[i]);motors.querySelectorAll('.motor').forEach((el,i)=>{el.querySelector('b').style.width=`${Math.abs(sim.actions[i])*100}%`;el.querySelector('small').textContent=sim.actions[i].toFixed(2);});document.querySelector('#feet').textContent=sim.legs.map((leg,i)=>`${leg}: ${o.footContacts[i]?'contact':'air'} (${o.footForces[i].toFixed(1)} N)`).join(' · ');document.querySelector('#clock').textContent=`${String(Math.floor(sim.time/60)).padStart(2,'0')}:${String(Math.floor(sim.time%60)).padStart(2,'0')}`;
}
const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.floor(w*renderer.getPixelRatio())||canvas.height!==Math.floor(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}controls.update();renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
