export function setupPlayback(onScene, selectView, onPolicies=()=>{}) {
  const panel=document.createElement('section');panel.id='playback-panel';panel.className='chart-card saved-panel';
  panel.innerHTML=`<div class="training-heading"><div><div class="eyebrow">SAVED POLICIES</div><h2>Watch what it has learned.</h2><p>Deterministic actions · no learning updates · matching seeds for fair comparisons</p></div><span id="playback-status">Connecting…</span></div><div class="training-controls"><label class="policy-choice">Checkpoint<select id="saved-policy"><option value="">Looking for saved policies…</option></select></label><button id="policy-refresh">Refresh list</button><label>Test stage<select id="policy-stage"><option value="saved">Checkpoint stage</option><option value="0">1 · 0.10 m/s</option><option value="1">2 · 0.20 m/s</option><option value="2">3 · 0.35 m/s</option><option value="3">4 · 0.50 m/s</option></select></label><label>Test seed<input id="policy-seed" type="number" min="0" max="999999" value="10001"></label><label>Trial seconds<input id="policy-seconds" type="number" min="1" max="120" value="20"></label><button id="policy-watch">Watch policy</button><button id="policy-pause">Pause playback</button><button id="policy-restart">Restart same trial</button></div><p id="policy-message" role="status">Checkpoints are read from your local runs folder. No policy files are changed during playback.</p><div class="training-metrics" id="playback-metrics"></div><h3>Completed playback trials</h3><p>Choose Initial policy and Latest saved policy from the same run, keeping the seed, duration and walking test stage identical. Results are kept in this browser connection, independently of training logs.</p><div class="results-scroll"><table id="policy-results"><thead><tr><th>Run / checkpoint</th><th>Seed / duration</th><th>Reward</th><th>Time upright</th><th>Forward distance</th><th>Motor work</th><th>Speed / target</th><th>Slip / foot cycles</th><th>Ending</th></tr></thead><tbody></tbody></table></div>`;
  document.querySelector('#training-panel').before(panel);
  const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/playback`);
  let connected=false,state={status:'idle'},entries=[];
  const choice=document.querySelector('#saved-policy'),message=document.querySelector('#policy-message');
  function send(command){if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(command));}
  function controls(){const loading=state.status==='loading';document.querySelector('#policy-watch').disabled=!connected||!choice.value||loading;document.querySelector('#policy-pause').disabled=!connected||!['playing','paused'].includes(state.status);document.querySelector('#policy-restart').disabled=!connected||!state.policy||loading;document.querySelector('#policy-refresh').disabled=!connected;document.querySelector('#policy-pause').textContent=state.status==='paused'?'Resume playback':'Pause playback';}
  function catalog(policies){entries=policies;onPolicies(entries);const old=choice.value;choice.replaceChildren();if(!entries.length){const option=new Option('No checkpoints found — train and save first','');choice.add(option);}for(const entry of entries){choice.add(new Option(`${entry.run_id} · ${entry.label} · ${entry.task} · ${new Date(entry.modified*1000).toLocaleString()}`,entry.id));}if(entries.some(entry=>entry.id===old))choice.value=old;controls();}
  socket.onopen=()=>{connected=true;controls();};
  socket.onclose=()=>{connected=false;document.querySelector('#playback-status').textContent='Disconnected';message.textContent='Playback disconnected. Restart the Python server and reload.';controls();};
  socket.onmessage=event=>{const next=JSON.parse(event.data);if(next.policies){catalog(next.policies);return;}if(next.commandError){message.textContent=next.commandError;return;}if(next.status==='loading'){state={...state,status:'loading'};document.querySelector('#playback-status').textContent='Loading…';controls();return;}state=next;document.querySelector('#playback-status').textContent=state.status;
    if(state.policy){message.textContent=`${state.policy.run_id} · ${state.policy.label} · ${state.policy.task} · saved at ${state.saved_steps.toLocaleString()} experience steps. Deterministic playback; weights stay fixed.`;
      const fields=[['Saved experience',state.saved_steps.toLocaleString()],['Trial seed',state.seed],['Elapsed time',`${state.scene.time.toFixed(1)} / ${state.seconds}s`],['Reward',state.metrics.reward.toFixed(2)],['Time upright',`${state.metrics.upright_seconds.toFixed(1)}s`],['Motor work',`${state.metrics.motor_work_joules.toFixed(1)} J`]];
      document.querySelector('#playback-metrics').innerHTML=fields.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('');onScene(state.scene);}
    const body=document.querySelector('#policy-results tbody');body.replaceChildren();for(const result of state.results||[]){const row=document.createElement('tr');const values=[`${result.policy} (${result.task})`,`${result.seed} / ${result.duration}s`,result.reward.toFixed(2),`${result.upright_seconds.toFixed(1)}s`,`${result.forward_distance.toFixed(2)}m`,`${result.motor_work_joules.toFixed(1)} J`,`${result.forward_speed.toFixed(3)} / ${result.target_speed??"—"} m/s`,`${result.mean_slip_speed.toFixed(3)} m/s / ${result.foot_cycles}`,result.reason];for(const value of values){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}body.append(row);}controls();
  };
  document.querySelector('#policy-refresh').onclick=()=>send({type:'list'});
  choice.onchange=controls;
  document.querySelector('#policy-watch').onclick=()=>{for(const id of ['policy-seed','policy-seconds'])if(!document.querySelector(`#${id}`).reportValidity())return;selectView();send({type:'load',policy:choice.value,seed:Number(document.querySelector('#policy-seed').value),seconds:Number(document.querySelector('#policy-seconds').value),stage:document.querySelector('#policy-stage').value==='saved'?'saved':Number(document.querySelector('#policy-stage').value)});};
  document.querySelector('#policy-pause').onclick=()=>send({type:state.status==='paused'?'resume':'pause'});
  document.querySelector('#policy-restart').onclick=()=>{selectView();send({type:'restart'});};
  controls();
  return {show:()=>{if(state.scene)onScene(state.scene);},refresh:()=>send({type:'list'})};
}
