// Visuals are direct measurements of the actor; they are not explanations of thoughts.
export function setupTraining(onScene) {
  const panel=document.createElement('section');panel.id='training-panel';
  panel.innerHTML=`<div class="training-heading"><div><div class="eyebrow">LEARNING LAB</div><h2>Watch experience become behaviour.</h2><p>One shared policy · independent joint control · no pretrained model</p></div><span id="training-status">Connecting…</span></div>
  <div class="training-controls"><label>Task<select id="training-task"><option value="balance">Balance first</option><option value="walk">Balance + move forward</option></select></label><label>Worlds<input id="training-worlds" type="number" min="1" max="8" value="1"></label><label>Experience steps<input id="training-steps" type="number" min="128" max="1000000" value="30000"></label><label>Seed<input id="training-seed" type="number" min="0" max="999999" value="1"></label><label>Viewing speed<select id="training-speed"><option value="realtime">Real time</option><option value="fast">Fast training · sampled frames</option></select></label><label class="check"><input type="checkbox" id="training-resume"> Continue saved policy</label><button id="training-start">Start learning</button><button id="training-pause">Pause learning</button><button id="training-stop">Stop & save</button></div>
  <p id="training-message" role="status">Training controls become available when the Python server connects.</p>
  <div class="training-metrics" id="training-metrics"></div>
  <div class="learning-grid"><div class="chart-card"><h3>Episode results</h3><label>Measure<select id="chart-measure"><option value="reward">Reward</option><option value="upright_seconds">Time upright (seconds)</option><option value="forward_distance">Forward displacement (metres)</option><option value="motor_work_joules">Motor work (joules)</option></select></label><canvas id="reward-chart" width="700" height="220"></canvas><p>Dots: completed training episodes. Line: rolling mean of the last 10. Exploration can make these noisy.</p></div><div class="chart-card"><h3>Does the policy perform better?</h3><canvas id="eval-chart" width="700" height="220"></canvas><p id="eval-summary">Fixed evaluation seeds compare the deterministic policy with neutral standing. Weight changes alone do not show improvement.</p></div></div>
  <div class="learning-grid brain-grid"><div class="chart-card"><h3>Actor network · 55 → 32 → 32 → 12</h3><canvas id="brain-chart" width="700" height="300"></canvas><p>Nodes: actual activations for the visible state. Lines: strongest 80 connections per layer; teal is positive, amber negative. This fixed network changes weights; it does not grow new neurons. Output nodes show action means; training adds exploration noise.</p></div><div class="chart-card"><h3>Inspect every connection</h3><div class="heatmap-controls"><label>Layer<select id="weight-layer"><option value="0">Inputs → hidden 1</option><option value="1">Hidden 1 → hidden 2</option><option value="2">Hidden 2 → joint outputs</option></select></label><label>Display<select id="weight-display"><option value="weights">Current weights</option><option value="changes">Change since run started</option></select></label></div><canvas id="weight-chart" width="700" height="300"></canvas><p id="weight-detail">Hover a cell to inspect its signed weight. Rows are destination neurons; columns are source neurons.</p></div></div>
  <div class="chart-card"><h3>Which inputs affect actions at this moment?</h3><div id="sensitivity"></div><p>Mean absolute gradient of the 12 action means with respect to each scaled input, at the visible state. This is local sensitivity, not proof of what the agent understands. It covers the actor only; PPO also trains a separate value network.</p></div>`;
  document.querySelector('main').after(panel);
  let state={status:'idle'},connected=false,lastRun=null;
  const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/training`);
  const message=document.querySelector('#training-message');
  function send(value){if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(value));}
  socket.onopen=()=>{connected=true;message.textContent='Choose a task and start. The 3D view will show training world 1.';updateControls();};
  socket.onclose=()=>{connected=false;document.querySelector('#training-status').textContent='Disconnected';message.textContent='Training connection lost. Restart the server and reload. A run may continue while its server is running.';updateControls();};
  socket.onerror=()=>{message.textContent='Cannot reach Python training server. Start physics.server first.';};
  socket.onmessage=event=>{const next=JSON.parse(event.data);if(next.commandError){message.textContent=next.commandError;return;}state=next;
    document.querySelector('#training-status').textContent=state.status;
    if(state.run_id!==lastRun){document.querySelector('#training-metrics').innerHTML='';lastRun=state.run_id;if(lastRun)message.textContent=`Run ${lastRun} · checkpoints and logs saved under runs/${lastRun}/`;
      if(state.config){document.querySelector('#training-task').value=state.config.task;document.querySelector('#training-worlds').value=state.config.worlds;document.querySelector('#training-steps').value=state.config.steps;document.querySelector('#training-seed').value=state.config.seed;document.querySelector('#training-speed').value=state.config.speed;}}
    if(state.error)message.textContent=state.error;
    if(state.scene)onScene(state.scene);
    const m=state.metrics;
    if(m){if(active())document.querySelector('#training-speed').value=m.speed;
      const fields=[['Experience',`${m.steps.toLocaleString()} / ${state.config.steps.toLocaleString()}`],['Episodes',m.episodes],['PPO epochs',m.updates],['Worlds',m.worlds],['Current reward',m.current_reward.toFixed(2)],['Weight change (L2)',state.brain.weightChange.toFixed(4)]];
      document.querySelector('#training-metrics').innerHTML=fields.map(([label,value])=>`<div><small>${label}</small><strong>${value}</strong></div>`).join('');}
    updateControls();draw();
  };
  function active(){return ['starting','running','paused','evaluating'].includes(state.status);}
  function updateControls(){document.querySelector('#training-start').disabled=!connected||active();for(const id of ['training-task','training-worlds','training-steps','training-seed','training-resume'])document.querySelector(`#${id}`).disabled=active();document.querySelector('#training-pause').disabled=!connected||!active();document.querySelector('#training-stop').disabled=!connected||!active();document.querySelector('#training-pause').textContent=state.status==='paused'?'Resume learning':'Pause learning';}
  document.querySelector('#training-start').onclick=()=>{for(const id of ['training-worlds','training-steps','training-seed'])if(!document.querySelector(`#${id}`).reportValidity())return;
    send({type:'start',task:document.querySelector('#training-task').value,worlds:Number(document.querySelector('#training-worlds').value),steps:Number(document.querySelector('#training-steps').value),seed:Number(document.querySelector('#training-seed').value),speed:document.querySelector('#training-speed').value,resume:document.querySelector('#training-resume').checked});};
  document.querySelector('#training-pause').onclick=()=>send({type:state.status==='paused'?'resume':'pause'});
  document.querySelector('#training-stop').onclick=()=>send({type:'stop'});
  document.querySelector('#training-speed').onchange=()=>{if(active())send({type:'speed',speed:document.querySelector('#training-speed').value});};
  for(const id of ['chart-measure','weight-layer','weight-display'])document.querySelector(`#${id}`).onchange=draw;
  function context(id){const canvas=document.querySelector(`#${id}`),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.font='11px system-ui';return [ctx,canvas.width,canvas.height];}
  function plot(id,series,baseline=null){const [ctx,w,h]=context(id);const values=series.flatMap(s=>s.values.map(v=>v.y));if(baseline!==null)values.push(baseline);if(!values.length){ctx.fillStyle='#8ea4a9';ctx.fillText('Waiting for completed episodes / evaluations…',25,50);return;}
    const low=Math.min(...values),high=Math.max(...values),range=Math.max(high-low,.1),min=low-range*.1,max=high+range*.1;const xmax=Math.max(1,...series.flatMap(s=>s.values.map(v=>v.x)));const px=x=>45+x/xmax*(w-70),py=y=>h-30-(y-min)/(max-min)*(h-55);
    ctx.strokeStyle='#294148';ctx.fillStyle='#8ea4a9';for(let i=0;i<4;i++){const v=min+(max-min)*i/3;ctx.beginPath();ctx.moveTo(45,py(v));ctx.lineTo(w-25,py(v));ctx.stroke();ctx.fillText(v.toFixed(range<1?2:1),0,py(v));}ctx.fillText('0',45,h-9);ctx.fillText(String(xmax),w-65,h-9);
    if(baseline!==null){ctx.setLineDash([5,5]);ctx.strokeStyle='#f0ba72';ctx.beginPath();ctx.moveTo(45,py(baseline));ctx.lineTo(w-25,py(baseline));ctx.stroke();ctx.setLineDash([]);}
    for(const s of series){ctx.strokeStyle=s.color;ctx.fillStyle=s.color;if(s.line){ctx.beginPath();s.values.forEach((v,i)=>i?ctx.lineTo(px(v.x),py(v.y)):ctx.moveTo(px(v.x),py(v.y)));ctx.stroke();}for(const v of s.values){ctx.beginPath();ctx.arc(px(v.x),py(v.y),s.line?2:3,0,Math.PI*2);ctx.fill();}}
  }
  function draw(){const history=state.history||[],measure=document.querySelector('#chart-measure').value;
    plot('reward-chart',[{color:'#698b8c',values:history.map(row=>({x:row.index,y:row[measure]}))},{color:'#70e6c4',line:true,values:history.map((row,i)=>({x:row.index,y:history.slice(Math.max(0,i-9),i+1).reduce((sum,v)=>sum+v[measure],0)/Math.min(i+1,10)}))}]);
    plot('eval-chart',[{color:'#70e6c4',line:true,values:(state.evaluations||[]).map(row=>({x:row.steps,y:row.reward}))}],state.baseline?.reward??null);
    const evaluation=state.evaluations?.at(-1);if(evaluation)document.querySelector('#eval-summary').textContent=`Held-out seeds ${evaluation.seeds.join(', ')} · ${evaluation.seconds}s trials. Teal: deterministic policy reward ${evaluation.reward.toFixed(2)}; dashed amber: neutral baseline ${state.baseline.reward.toFixed(2)}. Upright ${evaluation.upright_seconds.toFixed(1)}s, forward ${evaluation.forward_distance.toFixed(2)}m. Evaluated every ~1,024 experience steps and at run end.`;
    const brain=state.brain;if(!brain){for(const id of ['brain-chart','weight-chart'])context(id);document.querySelector('#sensitivity').textContent='Waiting for policy initialization…';return;}
    const [ctx,w,h]=context('brain-chart');const layers=brain.activations;const x=layer=>35+layer*(w-70)/(layers.length-1),y=(layer,node)=>20+node*(h-40)/Math.max(1,layers[layer].length-1);
    brain.weights.forEach((matrix,layer)=>{const edges=matrix.flatMap((row,to)=>row.map((value,from)=>({value,to,from}))).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,80);const max=Math.max(...edges.map(e=>Math.abs(e.value)),.001);for(const edge of edges){ctx.strokeStyle=edge.value>=0?`rgba(112,230,196,${.1+.6*Math.abs(edge.value)/max})`:`rgba(240,186,114,${.1+.6*Math.abs(edge.value)/max})`;ctx.beginPath();ctx.moveTo(x(layer),y(layer,edge.from));ctx.lineTo(x(layer+1),y(layer+1,edge.to));ctx.stroke();}});
    layers.forEach((values,layer)=>values.forEach((v,i)=>{ctx.fillStyle=v>=0?'#70e6c4':'#f0ba72';ctx.globalAlpha=.2+.8*Math.min(1,Math.abs(v));ctx.beginPath();ctx.arc(x(layer),y(layer,i),layer===0?2:3,0,Math.PI*2);ctx.fill();}));ctx.globalAlpha=1;
    const [heat,hw,hh]=context('weight-chart');const matrix=brain[document.querySelector('#weight-display').value][Number(document.querySelector('#weight-layer').value)];const maximum=Math.max(.00001,...matrix.flat().map(Math.abs));matrix.forEach((row,i)=>row.forEach((v,j)=>{heat.fillStyle=v>=0?'#70e6c4':'#f0ba72';heat.globalAlpha=.08+.92*Math.abs(v)/maximum;heat.fillRect(j*hw/row.length,i*hh/matrix.length,hw/row.length,hh/matrix.length);}));heat.globalAlpha=1;
    const ranked=brain.inputSensitivity.map((value,i)=>({value,name:brain.inputNames[i]})).sort((a,b)=>b.value-a.value).slice(0,8);const top=Math.max(.00001,...ranked.map(row=>row.value));document.querySelector('#sensitivity').innerHTML=ranked.map(row=>`<div class="sensitivity-row"><span>${row.name}</span><div><b style="width:${row.value/top*100}%"></b></div><small>${row.value.toFixed(4)}</small></div>`).join('');
  }
  document.querySelector('#weight-chart').onmousemove=event=>{if(!state.brain)return;const canvas=event.currentTarget,rect=canvas.getBoundingClientRect(),layer=Number(document.querySelector('#weight-layer').value),display=document.querySelector('#weight-display').value,matrix=state.brain[display][layer];const col=Math.min(matrix[0].length-1,Math.floor((event.clientX-rect.left)/rect.width*matrix[0].length)),row=Math.min(matrix.length-1,Math.floor((event.clientY-rect.top)/rect.height*matrix.length));document.querySelector('#weight-detail').textContent=`${layer===0?state.brain.inputNames[col]:`Neuron ${col+1}`} → ${layer===2?`Joint ${row+1}`:`Neuron ${row+1}`} · ${display==='weights'?'weight':'change'} ${matrix[row][col].toFixed(6)}`;};
  updateControls();draw();
  return {show:()=>{if(state.scene)onScene(state.scene);},isActive:active};
}
